In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
arr2 = np.array((7,8,9,1))
print(arr2)

[7 8 9 1]


In [12]:
ZeroDArray = np.array(1)
OneDArray = np.array([1,2,3,4,5])
twoDArray = np.array([[7,8,9,10],[11,12,13,14]])
ThreeDArray = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("Zero D Array =",ZeroDArray)
print("One D Array =",OneDArray)
print("Two D Array =",twoDArray)
print("Three D Array =",ThreeDArray)


Zero D Array = 1
One D Array = [1 2 3 4 5]
Two D Array = [[ 7  8  9 10]
 [11 12 13 14]]
Three D Array = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [15]:
print(ZeroDArray.ndim)
print(OneDArray.ndim)
print(twoDArray.ndim)
print(ThreeDArray.ndim)

0
1
2
3
